[package]
name = "spreadsheetconverter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "spreadsheetconverter"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
